# Generated by Django 5.2.6 on 2025-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_submission_feedback_submission_grdae_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='grdae',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
