# Generated by Django 5.2.6 on 2025-09-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True, help_text='학생이 제출 시 작성하는 설명입니다.'),
        ),
    ]
