# Generated by Django 5.2.6 on 2025-09-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submission_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_code',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
